blank_issues_enabled: true
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/yoanbernabeu/BLEF/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 📚 Documentation
    url: https://github.com/yoanbernabeu/BLEF/blob/main/blef_specification.md
    about: Read the full BLEF specification
  - name: 📖 Examples
    url: https://github.com/yoanbernabeu/BLEF/tree/main/examples
    about: Browse example BLEF files

